### ISSUE TITLE
Panics on debug

### ISSUE THREAD

**Issue by pigant** [richox/orz#13]
i tried this code (using the master branch)...

```rust
use orz::encode;
use orz::lz::LZCfg;

fn main() {
    let mut src = "Hola a todos!".as_bytes();
    let mut out: Vec<u8> = vec![];
    let cfg = LZCfg {
        match_depth: 48,
        lazy_match_depth1: 32,
        lazy_match_depth2: 16,
    };
    let result;
    result = encode(&mut src, &mut out, &cfg);
    match result {
        Ok(stat) => {
            println!(
                "source_size: {} -- target_size: {}",
                stat.source_size, stat.target_size
            );
        }
        Err(e) => eprintln!("Error: {:?}", e),
    };
}
```

Only if a run it with the flag release works.

![imagen](https://user-images.githubusercontent.com/14183160/89695054-ade59680-d8e0-11ea-8af3-7cdc5eac64b3.png)

**Comment by richox** [comment]
could you please provide the input data?

**Comment by pigant** [comment]
let mut src = "Hola a todos!".as_bytes()
that is ...
i know, it's very little data, but i was only testing using orz as a library.
I tried it with python using ctypes, and it works fantastic, using the dynamic lib.

**Comment by richox** [comment]
> let mut src = "Hola a todos!".as_bytes()
> that is ...
> i know, it's very little data, but i was only testing using orz as a library.
> I tried it with python using ctypes, and it works fantastic, using the dynamic lib.

it is reported by unchecked_index boundary checking from the unsafe code. but it is exactly safe since we have added some extra sentinel spaces after source/target buffers. the sentinel is used to reduce boundary checking and improve speed.

**Comment by richox** [comment]
> let mut src = "Hola a todos!".as_bytes()
> that is ...
> i know, it's very little data, but i was only testing using orz as a library.
> I tried it with python using ctypes, and it works fantastic, using the dynamic lib.

```
    let sbvec = &mut vec![0u8; LZ_BLOCK_SIZE + SBVEC_SENTINEL_LEN][.. LZ_BLOCK_SIZE];
    let tbvec = &mut vec![0u8; SBVEC_PREMATCH_LEN * 3];
```
this are the buffers we defined in `orz::encode()`. `sbvec` has some trailing buffer, so that when finding matches, we don't need to worry about overflow reading.
