### ISSUE TITLE
Can not run in win10 platform？

### ISSUE THREAD

**Issue by AnsonHooL** [richox/orz#14]
Hello.It is some trouble when I run the program in the win10 platform.Could you please give me some advises?

`**F:\orz-master\orz-master\target\debug>.\orz.exe  encode
1111111111111111111111111111111111
thread 'main' panicked at 'assertion index < len failed: index out of bounds: index = 16777251, len = 16777251', C:\Users\lenovo\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib/rustlib/src/rust\src\libcore\macros\mod.rs:16:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace**
`

**Comment by richox** [comment]
are you running under debug or release mode?
