### ISSUE TITLE
建议增加抑制info信息输出的选项。

### ISSUE THREAD

**Issue by hexiyou** [richox/orz#20]
程序可以解压数据后直接打印到标准输出，但目前貌似没有--quiet/--silent这样的选项可以关闭输出信息，很多小的文本文件经常需要在终端解压直接查看内容，建议增加上这样的选项。否则干扰了输出的文本，不太优雅。

![image](https://user-images.githubusercontent.com/1593944/117812803-d6962480-b294-11eb-954d-5c6028225047.png)

**Comment by richox** [comment]
已经有了 -s 或者 --silent

**Comment by hexiyou** [comment]
再看了一下，果然有了，失误了，之前只是 `orz --help`看了一下，没想到-s参数藏在 `orz decode --help`后边。
