### ISSUE TITLE
Any test?

### ISSUE THREAD

**Issue by longwusha** [richox/orz#3]
@richox 

It seems that there is no test code added in the project, how do we ensure that the compression and decompression results are correct. The current project version has reached 1.4, which means that the project function has been stable and can be used in the production environment. In this case, it is very necessary to add the corresponding test code.

**Comment by Artoria2e5** [comment]
There is some basic testing in `build.rs`, but yeah that is an AWFUL place for tests to happen. We also need documentations for the insides, some writeup justifying the unsafes, and unit tests.
