### ISSUE TITLE
Default compression level (3): Error: "invalid level: 3"

### ISSUE THREAD

**Issue by ehaupt** [richox/orz#30]
On FreeBSD I get (using `v1.6.2`):

```
Error: "invalid level: 3"
```

When using the default compression level (3) while encoding:

```
# orz encode /COPYRIGHT /COPYRIGHT.orz
Error: "invalid level: 3"
```

Same when specifying `-l 3`

```
# orz encode -l 3 /COPYRIGHT /COPYRIGHT.orz
Error: "invalid level: 3"
```

Dropping to `-l 2` seems to work:

```
# orz encode -l 2 /COPYRIGHT /COPYRIGHT.orz
[INFO] encode: 6109 bytes => 3147 bytes, 1.861MB/s
[INFO] statistics:
[INFO]   size:  6109 bytes => 3165 bytes
[INFO]   ratio: 51.81%
[INFO]   time:  0.016 sec
```

**Comment by richox** [comment]
-l3 is removed from the latest commits, the doc is not updated.

**Comment by ehaupt** [comment]
> -l3 is removed from the latest commits, the doc is not updated.

That would make sense. Thanks for clarifying.

**Comment by safinaskar** [comment]
@ehaupt , @richox , there was no any error in original docs. Docs said: `0..3`. And this doesn't include 3 (see https://doc.rust-lang.org/nightly/std/ops/struct.Range.html ). So, all was OK. :) (_I'm joking_)
