### ISSUE TITLE
Forbidden filename: checkout on WIndows 10 not possible

### ISSUE THREAD

**Issue by maklemenz** [richox/orz#5]
I want to give this a try, but git checkout and even zip download of this repo failes. I can't even copy the file contents by hand, as it is not possible to create a file named aux. The file extension doesn't even matter, it always leads to an exception.
Turnes out Windows has some reserved filenames:
https://kizu514.com/blog/forbidden-file-names-on-windows-10/

**Comment by richox** [comment]
thanks, renamed to 'auxility.rs'
