### ISSUE TITLE
Add Cargo.lock to the repository

### ISSUE THREAD

**Issue by jcgruenhage** [richox/orz#6]
For some context, see https://doc.rust-lang.org/cargo/faq.html#why-do-binaries-have-cargolock-in-version-control-but-not-libraries

Not having a Cargo.lock file seems to have broken the packaging for VoidLinux. See https://github.com/void-linux/void-packages/pull/15730

**Comment by richox** [comment]
released a new version v1.6.0 which contains Cargo.lock, try it please.

**Comment by jcgruenhage** [comment]
This was built successfully, thank you!
