### ISSUE TITLE
Provide a C API+ABI

### ISSUE THREAD

**Issue by Artoria2e5** [richox/orz#8]
The world out there still speaks C by and large. To let more people use the library, Orz should get a C API exported, so that people can use it from C++, Objective-C, Nim, Python, Node.js and everything else.

The [A little Rust with your C](https://rust-embedded.github.io/book/interoperability/rust-with-c.html) chapter explains how to make public functions C compatible and how to generate headers using cbindgen.

**Comment by richox** [comment]
thank you very much for your work!
i added a demo based on this c api in ./cffi-demo, it would be great if you can take some time to review it :)
